export type Region = {
  slug: string
  name: string
  county: string
  nearbyAreas: string[]
  coverageTitle: string
  areaGroups: string[]
}

export const REGIONS: Region[] = [
  { slug: "london", name: "London", county: "Greater London", nearbyAreas: ["Camden", "Hackney", "Lewisham", "Croydon"], coverageTitle: "We Buy Properties Across All London Areas", areaGroups: ["Westminster • Camden • Islington • Hackney", "Tower Hamlets • Greenwich • Lewisham • Southwark", "Lambeth • Wandsworth • Hammersmith • Kensington", "Chelsea • Fulham • Richmond • Kingston"] },
  { slug: "manchester", name: "Manchester", county: "Greater Manchester", nearbyAreas: ["Salford", "Didsbury", "Chorlton", "Stockport"], coverageTitle: "We Buy Properties Across Greater Manchester", areaGroups: ["Manchester • Salford • Stockport • Oldham", "Bolton • Bury • Rochdale • Tameside", "Trafford • Wigan • Altrincham • Sale", "Chorlton • Didsbury • Withington • Fallowfield"] },
  { slug: "birmingham", name: "Birmingham", county: "West Midlands", nearbyAreas: ["Edgbaston", "Selly Oak", "Erdington", "Sutton Coldfield"], coverageTitle: "We Buy Properties Across Birmingham & West Midlands", areaGroups: ["Birmingham • Solihull • Sutton Coldfield • Erdington", "Aston • Handsworth • Moseley • Kings Heath", "Edgbaston • Selly Oak • Harborne • Quinton", "West Bromwich • Walsall • Wolverhampton • Dudley"] },
  { slug: "liverpool", name: "Liverpool", county: "Merseyside", nearbyAreas: ["Anfield", "Allerton", "Kirkdale", "Bootle"], coverageTitle: "We Buy Properties Across Liverpool & Merseyside", areaGroups: ["Liverpool • Everton • Anfield • Toxteth", "Wavertree • Childwall • Allerton • Garston", "Woolton • Aigburth • Mossley Hill • West Derby", "Wirral • St Helens • Southport • Bootle"] },
  { slug: "leeds", name: "Leeds", county: "West Yorkshire", nearbyAreas: ["Headingley", "Roundhay", "Morley", "Horsforth"], coverageTitle: "We Buy Properties Across All Leeds Areas", areaGroups: ["City Centre • Headingley • Hyde Park • Woodhouse", "Chapel Allerton • Roundhay • Harehills • Burmantofts", "Kirkstall • Armley • Bramley • Wortley", "Holbeck • Beeston • Hunslet • Middleton"] },
  { slug: "bradford", name: "Bradford", county: "West Yorkshire", nearbyAreas: ["Shipley", "Bingley", "Keighley", "Ilkley"], coverageTitle: "We Buy Properties Across All Bradford Areas", areaGroups: ["City Centre • Shipley • Baildon • Saltaire", "Keighley • Bingley • Ilkley • Burley", "Manningham • Heaton • Thornton • Clayton", "Eccleshill • Wibsey • Wyke • Tong"] },
  { slug: "camden", name: "Camden", county: "Greater London", nearbyAreas: ["Kentish Town", "Hampstead", "Holborn", "Primrose Hill"], coverageTitle: "We Buy Properties Across All Camden Areas", areaGroups: ["Camden Town • King's Cross • Bloomsbury • Fitzrovia", "Hampstead • Highgate • Kentish Town • Chalk Farm", "Swiss Cottage • St John's Wood • Primrose Hill • Belsize Park", "Gospel Oak • Tufnell Park • Dartmouth Park • West Hampstead"] },
  { slug: "nottingham", name: "Nottingham", county: "Nottinghamshire", nearbyAreas: ["Beeston", "Arnold", "West Bridgford", "Mapperley"], coverageTitle: "We Buy Properties Across All Nottingham Areas", areaGroups: ["City Centre • The Park • Lace Market • Hockley", "West Bridgford • Beeston • Clifton • Wilford", "Carlton • Gedling • Arnold • Mapperley", "Bulwell • Aspley • Wollaton • Radford"] },
  { slug: "leicester", name: "Leicester", county: "Leicestershire", nearbyAreas: ["Oadby", "Wigston", "Evington", "Birstall"], coverageTitle: "We Buy Properties Across All Leicester Areas", areaGroups: ["City Centre • Stoneygate • Clarendon Park • Knighton", "Oadby • Wigston • Glen Parva • Blaby", "Evington • Aylestone • Kirby Muxloe • Narborough", "Hinckley • Market Harborough • Loughborough • Melton"] },
  { slug: "southampton", name: "Southampton", county: "Hampshire", nearbyAreas: ["Shirley", "Woolston", "Bitterne", "Portswood"], coverageTitle: "We Buy Properties Across All Southampton Areas", areaGroups: ["City Centre • Ocean Village • Bevois Valley • Portswood", "Eastleigh • Chandler's Ford • Hedge End • Botley", "Totton • Romsey • Fareham • Gosport", "Winchester • Basingstoke • Andover • New Forest"] },
  { slug: "sheffield", name: "Sheffield", county: "South Yorkshire", nearbyAreas: ["Hillsborough", "Ecclesall", "Crookes", "Dore"], coverageTitle: "We Buy Properties Across All Sheffield Areas", areaGroups: ["City Centre • Hillsborough • Walkley • Crookes", "Ecclesall • Fulwood • Hunters Bar • Endcliffe", "Heeley • Sharrow • Nether Edge • Millhouses", "Woodseats • Norton • Dore • Totley"] },
  { slug: "newcastle", name: "Newcastle", county: "Tyne and Wear", nearbyAreas: ["Jesmond", "Gosforth", "Heaton", "Wallsend"], coverageTitle: "We Buy Properties Across All Newcastle Areas", areaGroups: ["City Centre • Quayside • Jesmond • Gosforth", "Heaton • Byker • Walker • Wallsend", "Gateshead • Felling • Whickham • Blaydon", "Sunderland • Washington • Chester-le-Street • Durham"] },
  { slug: "bristol", name: "Bristol", county: "Bristol", nearbyAreas: ["Clifton", "Redland", "Southville", "Filton"], coverageTitle: "We Buy Properties Across All Bristol Areas", areaGroups: ["City Centre • Clifton • Redland • Cotham", "Westbury-on-Trym • Henleaze • Horfield • Bishopston", "Southville • Bedminster • Totterdown • Knowle", "Filton • Bradley Stoke • Thornbury • Chipping Sodbury"] },
  { slug: "lewisham", name: "Lewisham", county: "Greater London", nearbyAreas: ["Deptford", "Catford", "Brockley", "Forest Hill"], coverageTitle: "We Buy Properties Across All Lewisham Areas", areaGroups: ["Lewisham • Catford • Forest Hill • Honor Oak", "Deptford • New Cross • Telegraph Hill • Brockley", "Blackheath • Lee • Hither Green • Grove Park", "Sydenham • Downham • Bellingham • Crofton Park"] },
  { slug: "croydon", name: "Croydon", county: "Greater London", nearbyAreas: ["Purley", "Norbury", "Thornton Heath", "Sanderstead"], coverageTitle: "We Buy Properties Across All Croydon Areas", areaGroups: ["Croydon • East Croydon • West Croydon • Central Croydon", "Thornton Heath • Norbury • Selhurst • South Norwood", "Purley • Coulsdon • Kenley • Whyteleafe", "Addiscombe • Shirley • Waddon • Broad Green"] },
  { slug: "hammersmith", name: "Hammersmith", county: "Greater London", nearbyAreas: ["Fulham", "Shepherd's Bush", "Chiswick", "West Kensington"], coverageTitle: "We Buy Properties Across All Hammersmith Areas", areaGroups: ["Hammersmith • Fulham • Putney • Barnes", "Shepherd's Bush • White City • Holland Park • Brook Green", "Chelsea • West Brompton • Earl's Court • West Kensington", "Chiswick • Acton • Ealing • Gunnersbury"] },
  { slug: "havering", name: "Havering", county: "Greater London", nearbyAreas: ["Romford", "Hornchurch", "Upminster", "Rainham"], coverageTitle: "We Buy Properties Across All Havering Areas", areaGroups: ["Romford • Hornchurch • Upminster • Cranham", "Rainham • Elm Park • Harold Hill • Harold Wood", "Collier Row • Gidea Park • Emerson Park • Ardleigh Green", "North Ockendon • South Ockendon • Aveley • Purfleet"] },
  { slug: "redbridge", name: "Redbridge", county: "Greater London", nearbyAreas: ["Ilford", "Wanstead", "Woodford", "Barkingside"], coverageTitle: "We Buy Properties Across All Redbridge Areas", areaGroups: ["Ilford • Gants Hill • Cranbrook • Seven Kings", "Wanstead • South Woodford • Woodford Green • Woodford Bridge", "Barkingside • Fairlop • Aldborough Hatch • Newbury Park", "Hainault • Chigwell • Loughton • Buckhurst Hill"] },
  { slug: "barnet", name: "Barnet", county: "Greater London", nearbyAreas: ["Finchley", "Hendon", "Golders Green", "Edgware"], coverageTitle: "We Buy Properties Across All Barnet Areas", areaGroups: ["High Barnet • Chipping Barnet • New Barnet • East Barnet", "Finchley • North Finchley • East Finchley • West Finchley", "Mill Hill • Hendon • Colindale • Burnt Oak", "Edgware • Totteridge • Woodside Park • Friern Barnet"] },
  { slug: "hackney", name: "Hackney", county: "Greater London", nearbyAreas: ["Dalston", "Stoke Newington", "Shoreditch", "Hoxton"], coverageTitle: "We Buy Properties Across All Hackney Areas", areaGroups: ["Hackney Central • Hackney Downs • Hackney Wick • Homerton", "Shoreditch • Dalston • Kingsland • London Fields", "Stoke Newington • Clapton • Lower Clapton • Upper Clapton", "De Beauvoir • Haggerston • Hoxton • South Hackney"] },
  { slug: "enfield", name: "Enfield", county: "Greater London", nearbyAreas: ["Edmonton", "Southgate", "Palmers Green", "Winchmore Hill"], coverageTitle: "We Buy Properties Across All Enfield Areas", areaGroups: ["Enfield Town • Enfield Lock • Enfield Highway • Ponders End", "Winchmore Hill • Palmers Green • Southgate • New Southgate", "Edmonton • Lower Edmonton • Upper Edmonton • Bush Hill Park", "Cockfosters • Hadley Wood • Potters Bar • Crews Hill"] },
  { slug: "coventry", name: "Coventry", county: "West Midlands", nearbyAreas: ["Tile Hill", "Earlsdon", "Binley", "Foleshill"], coverageTitle: "We Buy Properties Across Coventry & Surrounding Areas", areaGroups: ["Coventry City Centre • Earlsdon • Canley • Tile Hill", "Foleshill • Holbrooks • Radford • Hillfields", "Kenilworth • Warwick • Leamington Spa • Rugby", "Nuneaton • Bedworth • Solihull • Redditch"] },
  { slug: "wolverhampton", name: "Wolverhampton", county: "West Midlands", nearbyAreas: ["Tettenhall", "Bilston", "Wednesfield", "Penn"], coverageTitle: "We Buy Properties Across Wolverhampton & Surrounding Areas", areaGroups: ["Wolverhampton City Centre • Tettenhall • Wednesfield • Bilston", "Penn • Codsall • Perton • Wombourne", "Stafford • Cannock • Telford • Bridgnorth", "Walsall • West Bromwich • Dudley • Stourbridge"] },
  { slug: "solihull", name: "Solihull", county: "West Midlands", nearbyAreas: ["Knowle", "Shirley", "Olton", "Chelmsley Wood"], coverageTitle: "We Buy Properties Across Solihull & Surrounding Areas", areaGroups: ["Solihull Town Centre • Shirley • Olton • Hall Green", "Knowle • Dorridge • Balsall Common • Meriden", "Birmingham • Coventry • Warwick • Stratford-upon-Avon", "Redditch • Bromsgrove • Tamworth • Lichfield"] },
  { slug: "walsall", name: "Walsall", county: "West Midlands", nearbyAreas: ["Bloxwich", "Aldridge", "Darlaston", "Willenhall"], coverageTitle: "We Buy Properties Across Walsall & Surrounding Areas", areaGroups: ["Walsall Town Centre • Bloxwich • Willenhall • Brownhills", "Aldridge • Streetly • Pelsall • Rushall", "Birmingham • Wolverhampton • West Bromwich • Dudley", "Cannock • Lichfield • Tamworth • Stafford"] },
  { slug: "west-bromwich", name: "West Bromwich", county: "West Midlands", nearbyAreas: ["Great Barr", "Smethwick", "Oldbury", "Tipton"], coverageTitle: "We Buy Properties Across West Bromwich & Surrounding Areas", areaGroups: ["West Bromwich Town Centre • Great Barr • Stone Cross • Hill Top", "Hateley Heath • Charlemont • Friar Park • Lambert's End", "Birmingham • Walsall • Dudley • Sandwell", "Oldbury • Smethwick • Tipton • Wednesbury"] },
  { slug: "dudley", name: "Dudley", county: "West Midlands", nearbyAreas: ["Brierley Hill", "Sedgley", "Netherton", "Kingswinford"], coverageTitle: "We Buy Properties Across Dudley & Surrounding Areas", areaGroups: ["Dudley Town Centre • Halesowen • Stourbridge • Brierley Hill", "Kingswinford • Sedgley • Coseley • Gornal", "Birmingham • West Bromwich • Wolverhampton • Walsall", "Kidderminster • Bromsgrove • Redditch • Worcester"] },
]

export const REGION_SLUGS = new Set(REGIONS.map((region) => region.slug))
